services:
    api:
        build:
            enabled: true
            context: ../../apis/core/pektin/api
            dockerfile: Dockerfile
        # image: your-registry/api
    db:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/db
            dockerfile: Dockerfile
        # image: your-registry/db
    dev:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/server/dev
            dockerfile: Dockerfile
        # image: your-registry/dev
    docs:
        build:
            enabled: true
            context: ../../apis/core/pektin/docs
            dockerfile: Dockerfile
        # image: your-registry/docs
    feoco:
        build:
            enabled: true
            context: ../../apis/core/pektin/feoco
            dockerfile: Dockerfile
        # image: your-registry/feoco
    image:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/addons/image
            dockerfile: Dockerfile
        # image: your-registry/image
    images:
        build:
            enabled: true
            context: ../../apis/cloud/filez/apps/backend/images
            dockerfile: Dockerfile
        # image: your-registry/images
    local:
        build:
            enabled: true
            context: ../../manager/install/old/tunnel/local
            dockerfile: Dockerfile
        # image: your-registry/local
    metadata:
        build:
            enabled: true
            context: ../../apis/cloud/filez/apps/backend/metadata
            dockerfile: Dockerfile
        # image: your-registry/metadata
    metadata:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/addons/metadata
            dockerfile: Dockerfile
        # image: your-registry/metadata
    mpm:
        build:
            enabled: true
            context: ../../utils/mpm
            dockerfile: Dockerfile
        # image: your-registry/mpm
    muzik:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/addons/muzik
            dockerfile: Dockerfile
        # image: your-registry/muzik
    pektin-resource-controller:
        build:
            enabled: true
            context: ../../operators/pektin-resource-controller
            dockerfile: Dockerfile
        # image: your-registry/pektin-resource-controller
    ribston:
        build:
            enabled: true
            context: ../../apis/core/pektin/ribston
            dockerfile: Dockerfile
        # image: your-registry/ribston
    server:
        build:
            enabled: true
            context: ../../apis/cloud/filez/server
            dockerfile: Dockerfile
        # image: your-registry/server
    server:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/server
            dockerfile: Dockerfile
        # image: your-registry/server
    server:
        build:
            enabled: true
            context: ../../apis/core/pektin/server
            dockerfile: Dockerfile
        # image: your-registry/server
    tests:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/addons/video/tests
            dockerfile: Dockerfile
        # image: your-registry/tests
    vault-resource-controller:
        build:
            enabled: true
            context: ../../operators/vault-resource-controller
            dockerfile: Dockerfile
        # image: your-registry/vault-resource-controller
    verkehr:
        build:
            enabled: true
            context: ../../apis/core/pektin/verkehr
            dockerfile: Dockerfile
        # image: your-registry/verkehr
    video:
        build:
            enabled: true
            context: ../../apis/cloud/filez-old/addons/video
            dockerfile: Dockerfile
        # image: your-registry/video
    web:
        build:
            enabled: true
            context: ../../apis/cloud/filez/web
            dockerfile: Dockerfile
        # image: your-registry/web
    website:
        build:
            enabled: true
            context: ../../website
            dockerfile: Dockerfile
        # image: your-registry/website
    zertificat:
        build:
            enabled: true
            context: ../../apis/core/pektin/zertificat
            dockerfile: Dockerfile
        # image: your-registry/zertificat
    zitadel-resource-controller:
        build:
            enabled: true
            context: ../../operators/zitadel-resource-controller
            dockerfile: Dockerfile
        # image: your-registry/zitadel-resource-controller
