services:
    pektin-resource-controller:
        build:
            context: "."
            dockerfile: Dockerfile
            tags:
                - ${REGISTRY:-localhost:5000}/${SERVICE_NAME}
            additional_contexts:
                mows-common-rust: ../../utils/mows-common-rust
                pektin-common: ../../apis/core/pektin/common
                lock: ../../
            args:
                - PROFILE=${PROFILE:-dev} # dev or release
                - SERVICE_NAME=${SERVICE_NAME}
                - APP_STAGE_IMAGE=${APP_STAGE_IMAGE:-alpine}
