apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verkehrresources.verkehr.k8s.mows.cloud
spec:
  group: verkehr.k8s.mows.cloud
  names:
    categories: []
    kind: VerkehrResource
    plural: verkehrresources
    shortNames:
    - vr
    singular: verkehrresource
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1
    schema:
      openAPIV3Schema:
        description: Custom kubernetes resource for applying verkehr configurations.
        properties:
          spec:
            oneOf:
            - required:
              - ingressRouteHttp
            properties:
              ingressRouteHttp:
                properties:
                  entrypoints:
                    items:
                      type: string
                    type: array
                  routes:
                    items:
                      properties:
                        kind:
                          type: string
                        match:
                          type: string
                        services:
                          items:
                            properties:
                              name:
                                type: string
                              port:
                                format: uint16
                                minimum: 0.0
                                type: integer
                              weight:
                                format: uint32
                                minimum: 0.0
                                nullable: true
                                type: integer
                            required:
                            - name
                            - port
                            type: object
                          type: array
                      required:
                      - kind
                      - match
                      - services
                      type: object
                    type: array
                required:
                - entrypoints
                - routes
                type: object
            type: object
          status:
            nullable: true
            properties:
              created:
                type: boolean
            required:
            - created
            type: object
        required:
        - spec
        title: VerkehrResource
        type: object
    served: true
    storage: true
    subresources:
      status: {}
